<?php
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/stream-data.php';
$stream = getStudyStream(trim($_GET['slug'] ?? ''));
if (!$stream) { http_response_code(404); $pageTitle='Course category not found'; require __DIR__.'/includes/header.php'; echo '<main class="container py-5"><h1>Course category not found</h1></main>'; require __DIR__.'/includes/footer.php'; exit; }
$pageTitle = $stream['title'] . ' – Courses & Admissions 2026';
$pageDescription = 'Explore ' . strtolower($stream['title']) . ', eligibility, admission routes, selection checklist and Jaipur college options for 2026.';
$canonicalUrl = 'https://collegeinjaipur.com/courses/' . $stream['slug'] . '/';
$colleges = getColleges([], 12);
$structuredData = [
    ['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$stream['title'],'url'=>$canonicalUrl,'description'=>$pageDescription],
    ['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>[
        ['@type'=>'Question','name'=>'How should I choose a '.$stream['name'].' college in Jaipur?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Compare current recognition, curriculum, faculty, total fees, location, facilities and programme-specific outcomes using official documents.']],
        ['@type'=>'Question','name'=>'Are admission rules and fees the same every year?','acceptedAnswer'=>['@type'=>'Answer','text'=>'No. Eligibility, entrance routes, fees, seats and deadlines can change. Verify the current official prospectus before applying.']],
    ]],
];
require __DIR__ . '/includes/header.php';
?>
<main>
<section class="page-heading py-5"><div class="container"><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="<?= url() ?>">Home</a></li><li class="breadcrumb-item"><a href="<?= url('courses.php') ?>">Courses</a></li><li class="breadcrumb-item active"><?= e($stream['name']) ?></li></ol></nav><div class="row align-items-center g-4"><div class="col-lg-8"><span class="eyebrow">Jaipur course guide</span><h1 class="display-5 fw-bold"><?= e($stream['title']) ?></h1><p class="lead text-secondary mb-0">Compare programmes, admission routes and practical selection factors for the 2026 cycle.</p></div><div class="col-lg-4 text-lg-end"><i class="bi bi-<?= e($stream['icon']) ?> stream-hero-icon"></i></div></div></div></section>
<section class="container py-5"><div class="row g-4"><div class="col-lg-8"><section class="mb-5"><h2 class="h3 fw-bold"><?= e($stream['name']) ?> courses and options</h2><p><?= e($stream['course_examples']) ?> are available across different institution types in Jaipur. Course names alone are not enough: compare curriculum depth, practical exposure, affiliation or recognition, examination system and the exact campus offering the programme.</p></section><section class="mb-5"><h2 class="h3 fw-bold">Eligibility and admission route</h2><p><?= e($stream['eligibility']) ?></p><div class="alert alert-warning">Admissions, fees, approvals and seat availability change. Use this page for discovery and confirm every decision with the institution and applicable regulator.</div></section><section class="mb-5"><h2 class="h3 fw-bold">Career direction</h2><p>Common directions include <?= e($stream['careers']) ?>. Outcomes depend on the programme, the student’s skills and verified institution-level opportunities—not only the college name.</p></section><section class="mb-5"><h2 class="h3 fw-bold">Selection checklist</h2><div class="row g-3"><?php foreach(['Current recognition or approval','Programme-wise curriculum','Complete fee breakup','Faculty and practical facilities','Internship and placement evidence','Travel, hostel and daily cost'] as $item): ?><div class="col-md-6"><div class="check-card"><i class="bi bi-check-circle-fill"></i><span><?= e($item) ?></span></div></div><?php endforeach; ?></div></section><?php if(in_array($stream['slug'], ['bca','mca','engineering'], true)): ?><section class="mb-5"><h2 class="h3 fw-bold">Practical coding & IT skill resources in Jaipur</h2><p>Alongside your degree research, students preparing for software and technology careers can explore practical course options at <a href="https://forskcodingschool.com/" target="_blank" rel="noopener">Forsk Coding School</a> and <a href="https://jaipurengineers.com/" target="_blank" rel="noopener">Jaipur Engineers</a>. Compare curriculum, learning mode and current batch details directly before enrolling.</p></section><?php endif; ?></div><aside class="col-lg-4"><div class="card border-0 shadow-sm p-4 sticky-lg-top filter-card"><h2 class="h5 fw-bold">Need a shortlist?</h2><p class="small text-secondary">Share your budget, qualification and preferred course.</p><a class="btn btn-primary" href="<?= url('contact.php?course='.urlencode($stream['name'])) ?>">Get admission guidance</a></div></aside></div></section>
<section class="course-strip py-5"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">Explore institutions</span><h2 class="h3 fw-bold mb-0">College profiles in Jaipur</h2></div><a class="btn btn-outline-primary" href="<?= url('colleges.php?q='.urlencode($stream['name'])) ?>">View filtered list</a></div><div class="row g-4"><?php foreach(array_slice($colleges,0,6) as $college): ?><div class="col-md-6 col-xl-4"><article class="card college-card h-100 border-0 shadow-sm"><div class="card-body p-4"><span class="badge bg-primary-subtle text-primary mb-2"><?= e($college['type']) ?></span><h3 class="h5 fw-bold"><?= e($college['name']) ?></h3><p class="small text-secondary"><i class="bi bi-geo-alt"></i> <?= e($college['area']) ?>, Jaipur</p><a href="<?= url('college/'.$college['slug'].'/') ?>" class="stretched-link">View profile</a></div></article></div><?php endforeach; ?></div></div></section>
<section class="container py-5"><h2 class="h3 fw-bold">Frequently asked questions</h2><div class="accordion mt-3" id="streamFaq"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#streamFaq1">How should I choose a <?= e($stream['name']) ?> college in Jaipur?</button></h3><div id="streamFaq1" class="accordion-collapse collapse show" data-bs-parent="#streamFaq"><div class="accordion-body">Compare current recognition, curriculum, faculty, total fees, location, facilities and programme-specific outcomes using official documents.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#streamFaq2">Are admission rules and fees the same every year?</button></h3><div id="streamFaq2" class="accordion-collapse collapse" data-bs-parent="#streamFaq"><div class="accordion-body">No. Verify current eligibility, entrance routes, fees, seats and deadlines in the official prospectus.</div></div></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
