<?php
require_once __DIR__ . '/../includes/blog-data.php';
$post=getBlogPost(trim($_GET['slug']??''));
if(!$post){http_response_code(404);$pageTitle='Guide not found';require __DIR__.'/../includes/header.php';echo '<main class="container py-5"><h1>Guide not found</h1><a href="'.url('blog/').'">Browse blog</a></main>';require __DIR__.'/../includes/footer.php';exit;}
$pageTitle=$post['title'].' | College in Jaipur'; $pageDescription=$post['description']; $sections=blogArticleSections($post);
$canonicalUrl='https://collegeinjaipur.com/blog/'.$post['slug'].'/';
$robotsContent='noindex,follow';
require __DIR__ . '/../includes/header.php';
?>
<main><article><header class="page-heading py-5"><div class="container"><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="<?= url() ?>">Home</a></li><li class="breadcrumb-item"><a href="<?= url('blog/') ?>">Blog</a></li><li class="breadcrumb-item active"><?= e($post['category']) ?></li></ol></nav><span class="badge bg-primary-subtle text-primary mb-3"><?= e($post['category']) ?></span><h1 class="display-6 fw-bold col-lg-10"><?= e($post['title']) ?></h1><p class="lead text-secondary col-lg-9"><?= e($post['description']) ?></p><div class="small text-secondary">Updated for 2026 · 8 minute read · College in Jaipur Editorial Team</div></div></header>
<div class="container py-5"><div class="row justify-content-center"><div class="col-lg-8 blog-content"><?php foreach($sections as $index=>[$heading,$body]): ?><section class="mb-5"><h2 class="h3 fw-bold"><?= e($heading) ?></h2><p><?= e($body) ?></p><?php if($index===3): ?><div class="alert alert-info"><strong>Useful tip:</strong> Official fee receipt, prospectus aur refund policy ki copy save karke rakhein.</div><?php endif; ?></section><?php endforeach; ?>
<section class="mb-5"><h2 class="h3 fw-bold">Frequently asked questions</h2><div class="accordion" id="faq"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#faq1">Kya is guide ki admission details final hain?</button></h3><div id="faq1" class="accordion-collapse collapse show" data-bs-parent="#faq"><div class="accordion-body">Nahi. Admission dates, fees, courses aur rules change ho sakte hain. Current official notification verify karein.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#faq2">College compare karte waqt sabse important factor kya hai?</button></h3><div id="faq2" class="accordion-collapse collapse" data-bs-parent="#faq"><div class="accordion-body">Academic fit, recognition, total cost, location aur programme-specific outcomes ko saath mein evaluate karein.</div></div></div></div></section>
<div class="card border-0 bg-primary text-white p-4"><h2 class="h4 fw-bold">Jaipur colleges shortlist karne mein help chahiye?</h2><p>Apni course preference aur budget share karein.</p><a class="btn btn-warning align-self-start" href="<?= url('contact.php') ?>">Request admission guidance</a></div></div></div></div></article></main>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$post['title'],'description'=>$post['description'],'author'=>['@type'=>'Organization','name'=>'College in Jaipur'],'publisher'=>['@type'=>'Organization','name'=>'College in Jaipur','url'=>'https://collegeinjaipur.com'],'mainEntityOfPage'=>'https://collegeinjaipur.com/blog/'.$post['slug'].'/'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script>
<?php require __DIR__ . '/../includes/footer.php'; ?>
